Fix datastream mongodb to firestore breakage. (#3123)
* Fix datastream mongodb to firestore breakage.

The template job is currently failing due to version mismatch between `mongodb-driver-sync`
and `mongodb-driver-core`:

```
com.google.cloud.teleport.v2.common.UncaughtExceptionLogger - The template launch failed.
java.lang.NoSuchMethodError: 'com.mongodb.internal.connection.StreamFactoryFactory com.mongodb.internal.connection.StreamFactoryHelper.getSyncStreamFactoryFactory(com.mongodb.connection.TransportSettings, com.mongodb.spi.dns.InetAddressResolver)'
	at com.mongodb.client.MongoClients.create(MongoClients.java:120)
	at com.mongodb.client.MongoClients.create(MongoClients.java:57)
	at com.google.cloud.teleport.v2.templates.DataStreamMongoDBToFirestore.run(DataStreamMongoDBToFirestore.java:455)
	at com.google.cloud.teleport.v2.templates.DataStreamMongoDBToFirestore.main(DataStreamMongoDBToFirestore.java:400)
```

This change is rolling back a previous
[commit](https://github.com/GoogleCloudPlatform/DataflowTemplates/commit/aa099da8cc546e371fb44e8aab4566053ef4e355).

* Fix tests.

* Use properties to enforce consistency between driver sync and driver core.

---------

Co-authored-by: Louis Kuang <louiskuang@google.com>