Allow empty string to be used for source and destination database
An INVALID_ARGUMENT is thrown when `(default)` is used as the source or destination database.

```
com.google.datastore.v1.client.DatastoreException: (default) is not a valid databaseId. Please use the empty string to denote the (default) database
```