Reduce the test name to fulfill the 30 chars limit
I renamed the test, and they now failed because of a table length limit:
java.lang.IllegalArgumentException: Table name testPostgreSqlToBigQueryDedicated cannot be longer than 30 characters.
	at com.google.cloud.teleport.v2.templates.PostgreSQLToBigQueryIT.testPostgreSqlToBigQueryDedicated(PostgreSQLToBigQueryIT.java:95)