upgraded protobuf-java to 3.21.9 to resolve the conflicts with bigquery api
With protobuf-java v3.21.5, got following error when running pipeline to read data from BigQueryIO.
Caused by: java.lang.NoSuchMethodError: 'boolean com.google.protobuf.GeneratedMessageV3$Builder.parseUnknownField(com.google.protobuf.CodedInputStream, com.google.protobuf.ExtensionRegistryLite, int)'
	com.google.cloud.bigquery.storage.v1.ReadSession$Builder.mergeFrom(ReadSession.java:4665)